// import Providers from "@/components/provideres";


// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

// export default function RootLayout({
//     childern,
// }: {
//     childern: React.ReactNode;
// }) {
//     return (
//         <html lang="en">
//             <body>
//                <Providers>{childern}
//                </Providers>
//             </body>
//         </html>
//     )
// }