// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Inam",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import "./globals.css";
import Navbar from './components/Navbar'
import About from './components/About'
import Home from './components/Home'
import Question from './components/Question'
export default function RootLayout({ children}) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar />
        <Home/>
        <About/> */}
        <Question/>
        {children}
      </body>
    </html>
  );
}
